services:
      - type: web
        plan: free
        name: WarBot
        env: python
        buildCommand: pip install -U -r requirements.txt
        startCommand: python server.py & bash warbot
        repo: https://github.com/Tanvi555/suggar_mmy_userbot   
        branch: master
        envVars:
          - key: ABUSE
            sync: false
          - key: APP_ID
            sync: false
          - key: API_HASH
            sync: false
          - key: BOT_TOKEN
            sync: false
          - key: ENV
            value: ANYTHING
          - key: STRING_SESSION
            sync: false
          - key: DATABASE_URL
            sync: false
          - key: PYTHON_VERSION
            value: 3.10.6
            
        autoDeploy: false
